### ISSUE TITLE
Some advice from Ubidots

### ISSUE THREAD

**Issue by jotathebest** [AloriumTechnology/UbidotsXLR8#1]
Hi there, I tried to make a commit but the repository seems to be private, so I would like to add some feedback:

- The variable bodyPosInit is declared in the methods to get values but it is never used. You should delete it to save memory.

- There are several free() missings calls that should be declared, i.e on line 119 if the device cannot connect that memory space is not free. Same happens on lines 159, 204 and 232 with variables data and response.

- Avoid to use Strings objects because they make use of the heap memory, on line 310 you may use the dtostrf() function to cast your float type variables to char type.

- Update the authors of the library, actually, Mateo Velez is not the original maker of the library.

Feel free to take or not these suggestions, we are glad to know that you developed a library for our platform, thank you so much.

Have a nice day.

**Comment by crakerbr-superiontech** [comment]
Thanks for the information! The repository must have been set to private by default, internally we don't use GitHub for repo control so changes have to be rolled in manually anyway. You're right though, I must have left variables from an original version of the code and and not checked to see if they were used, and I'll go through and clean up those frees as well.

I was trying to avoid using Strings, and thought I could use %f in my sprintf function but it looks like that was not implemented in the Arduino compiler and I came up with a less-efficient workaround. Thanks for pointing out the dtostrf function.

I received code from Jason in our office and updated it, and I'm not sure where he received it from but I presume the code he had had the Mateo Velez author line in it. I'll check in with him, though he happens to be on vacation for a few days. Do you know who the correct original author should be? I see several of the GitHub libraries credited with Mateo, María Carlina Hernández, and Jose Garcia (you I believe).

Thanks again for the helpful information!

**Comment by jotathebest** [comment]
Hi there, yes, I am Jose Garcia, the internal hardware leader at Ubidots. I am glad that my feedback is valuable for you, remember that we are to help you as much as we can to integrate Alorium with Ubidots.

Have a nice rest of your day.

**Comment by crakerbr-superiontech** [comment]
Changes have been made & checked, the updated library is available through the Arduino IDE
